#!/bin/bash
#
# Run ffmpeg in a container
#


set -e
declare INPUT
declare OUTPUT
declare INPUT_DIR
declare OUTPUT_DIR
declare INPUT_FILENAME
declare OUTPUT_FILENAME

TAG="latest"
IMAGE="cafetime/ffmpeg:$TAG"
FFMPEG_OPTIONS="ffmpeg"

FROM_DIR="/opt/from/"
TO_DIR="/opt/to/"


# Setup options for connecting to docker host
if [ -z "$DOCKER_HOST" ]; then
    DOCKER_HOST="/var/run/docker.sock"
fi
if [ -S "$DOCKER_HOST" ]; then
    DOCKER_ADDR="-v $DOCKER_HOST:$DOCKER_HOST -e DOCKER_HOST"
else
    DOCKER_ADDR="-e DOCKER_HOST -e DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH"
fi

# Only allocate tty if we detect one
if [ -t 1 ]; then
    DOCKER_RUN_OPTIONS="-t"
fi
if [ -t 0 ]; then
    DOCKER_RUN_OPTIONS="$DOCKER_RUN_OPTIONS -i"
fi


args=$#
OUTPUT=${!args}
if [ "echo $OUTPUT | grep /" == "" ];then
	OUTPUT_DIR=""
else
	OUTPUT_DIR=${OUTPUT%/*}
fi
OUTPUT_FILENAME=${OUTPUT##*/}
until [ $# -eq 0 ]
do
	if [ "$1" == "-i" ]; then
		INPUT=$2
		if [ "echo $INPUT | grep /" == "" ];then
			INPUT_DIR=""
		else
			INPUT_DIR=${INPUT%/*}
		fi
		INPUT_FILENAME=${INPUT##*/} 
		FFMPEG_OPTIONS=$FFMPEG_OPTIONS" "$1" $FROM_DIR$INPUT_FILENAME"
		shift;
	else
		if [ "$2" == "" ];then
			FFMPEG_OPTIONS=$FFMPEG_OPTIONS" $TO_DIR$OUTPUT_FILENAME"
		else
			FFMPEG_OPTIONS=$FFMPEG_OPTIONS" "$1
		fi
	fi
	shift;
done

if [ "" == "$INPUT_DIR" ];then
	INPUT_DIR=$(pwd)
fi
if [ "" == "$OUTPUT_DIR" ];then
	OUTPUT_DIR=$(pwd)
fi
echo "docker run --rm $DOCKER_RUN_OPTIONS $DOCKER_ADDR -v $INPUT_DIR:$FROM_DIR -v $OUTPUT_DIR:$TO_DIR -w $FROM_DIR $IMAGE $FFMPEG_OPTIONS"
exec docker run --rm $DOCKER_RUN_OPTIONS $DOCKER_ADDR -v $INPUT_DIR:$FROM_DIR -v $OUTPUT_DIR:$TO_DIR -w $FROM_DIR $IMAGE $FFMPEG_OPTIONS
